# OIC-158 TEM Nuclei Segmentation
Packages to import

In [63]:
import napari
import numpy as np
import pyclesperanto as cle
import skimage as sk
from skimage.io import imread, imsave
import pandas as pd
import os
from glob import glob
import matplotlib as mpl
import matplotlib.pyplot as plt

All functions for pipeline

In [64]:
#Create a 25-pixel wide band along perimeter of nucleus
def band_25_pixels(masks,footprint):
    eroded = [sk.morphology.erosion(mask, footprint=footprint) for mask in masks]
    bands = [masks[i] - eroded[i] for i in range(len(masks))]
    return bands

#Threshold the dense regions within whole image
def norm_and_threshold(imgs,match_img,max_hole=100,min_object=20):
    adpt_norm = [sk.exposure.equalize_adapthist(img) for img in imgs]
    match_img_adpt_norm = sk.exposure.equalize_adapthist(match_img)
    matched_hist = [sk.exposure.match_histograms(img, match_img_adpt_norm) for img in adpt_norm]
    filtered = []
    for img in matched_hist:
        yen = sk.filters.threshold_yen(img)
        mask = img < yen
        dilate = sk.morphology.dilation(mask)
        filtered.append(sk.morphology.remove_small_objects(sk.morphology.remove_small_holes(dilate,area_threshold=max_hole),min_size=min_object))
    return filtered, matched_hist

#Get dense roi masks within the nuclei and 25-pixel band
def dense_rois_in_nuclei_and_band(dense_roi_masks, band_25_pixels, relabel_nuc_masks):
    dense_roi_in_nuclei = [dense_roi_masks[i] * relabel_nuc_masks[i] for i in range(len(relabel_nuc_masks))]
    dense_roi_in_band = [dense_roi_in_nuclei[i] * band_25_pixels[i] for i in range(len(band_25_pixels))]
    return dense_roi_in_nuclei, dense_roi_in_band

#merge masks and image into array for measurements
def merge_masks_image(imgs,original_nuc_masks,relabel_nuclei_masks,band_25_pixels,dense_roi_in_nuclei,dense_roi_in_band):
    merged_stacks = []
    for i in range(len(imgs)):
        stack = np.stack([imgs[i],original_nuc_masks[i],relabel_nuclei_masks[i],band_25_pixels[i],dense_roi_in_nuclei[i],dense_roi_in_band[i]],axis=-1)
        merged_stacks.append(stack)
    return merged_stacks

#Get heterochromatin and band areas as lists
def heterochromatin_and_band_areas(dense_roi_in_band, band_25_pixels, scale):
    all_heterochromatin_areas = []
    all_band_areas = []
    all_norm_areas = []
    for i in range(len(band_25_pixels)):
        i_heterochromatin_areas = []
        i_band_areas = []
        i_norm_areas = []
        band_props = sk.measure.regionprops(band_25_pixels[i],spacing=scale)
        heterochromatin_props = sk.measure.regionprops(dense_roi_in_band[i],spacing=scale)
        for j in range(len(band_props)):
            band_area = band_props[j].area
            heterochromatin_area = heterochromatin_props[j].area
            norm_area = heterochromatin_area/band_area
            i_heterochromatin_areas.append(heterochromatin_area)
            i_band_areas.append(band_area)
            i_norm_areas.append(norm_area)
        all_heterochromatin_areas.append(i_heterochromatin_areas)
        all_band_areas.append(i_band_areas)
        all_norm_areas.append(i_norm_areas)
    return all_heterochromatin_areas, all_band_areas, all_norm_areas

#Get measurements for all compartments and merge dataframes together (run in loop for all images)
def get_measurements(merged_stacks,props,scale,all_heterochromatin_areas, all_band_areas, all_norm_areas):
    heterochromatin_areas_df = pd.Series(all_heterochromatin_areas,name='heterochromatin_area_in_band_um^2')
    band_areas_df = pd.Series(all_band_areas, name='25-pixel_band_area_um^2')
    norm_area_df = pd.Series(all_norm_areas, name='norm_area_heterochromatin_in_band')
    nuc_measurements_table = sk.measure.regionprops_table(merged_stacks[:,:,2],merged_stacks,props,spacing=scale)
    nuc_regionprops = sk.measure.regionprops(merged_stacks[:,:,2],spacing=scale)
    circularity = []
    for i in range(len(nuc_regionprops)):
        nuc_area = nuc_regionprops[i].area
        nuc_perimeter = nuc_regionprops[i].perimeter
        circularity.append(4*np.pi*nuc_area/nuc_perimeter**2)
    circularity = pd.Series(circularity,name='nuc_circularity')
    nuc_df = pd.DataFrame.from_dict(nuc_measurements_table)
    nuc_df.rename(columns={'label':'object_ID','area':'Nuc_area_um^2','intensity_max-0':'Image_intensity_max', 'intensity_max-1':'Cell_ID',
                           'intensity_max-2':'Nuc_region_ID','intensity_max-3':'Band_ID','intensity_max-4':'Dense_nuc_regions_ID',
                           'intensity_max-5':'Heterochromatin_band_ID','equivalent_diameter_area':'equivalent_diameter_area_um^2',
                           'perimeter':'perimeter_um'},inplace=True)
    df = pd.concat([nuc_df,circularity,heterochromatin_areas_df,band_areas_df,norm_area_df], axis=1)
    return df

#save images as tiffs and dataframes as csv (run in loop for all images along with get measurements function)
def save_df_and_images(df,matched_hist,bands,dense_roi_in_nuclei,dense_roi_in_band,save_loc,img_files):
    matched_hist_path = os.path.join(save_loc,'processed_imgs')
    bands_path = os.path.join(save_loc,'nuc_bands')
    dense_roi_nuc_path = os.path.join(save_loc,'dense_rois_in_nuc')
    dense_roi_band_path = os.path.join(save_loc,'dense_rois_in_band')
    df_path = os.path.join(save_loc,'measurements')
    img_name = os.path.basename(img_files)
    imsave(os.path.join(matched_hist_path,'matched_histogram_'+img_name[:-4]+'.tif'),matched_hist,check_contrast=False)
    imsave(os.path.join(bands_path,'25-pixel_band_'+img_name[:-4]+'.tif'),bands,check_contrast=False)
    imsave(os.path.join(dense_roi_nuc_path,'dense_roi_nuc_'+img_name[:-4]+'.tif'),dense_roi_in_nuclei,check_contrast=False)
    imsave(os.path.join(dense_roi_band_path,'dense_roi_nuc_'+img_name[:-4]+'.tif'),dense_roi_in_band,check_contrast=False)
    df.to_csv(os.path.join(df_path,'measurements_'+img_name[:-4]+'.csv'))

def create_folders(save_loc):
    try:
        os.makedirs(os.path.join(save_loc,'processed_imgs'))
        os.makedirs(os.path.join(save_loc,'nuc_bands'))
        os.makedirs(os.path.join(save_loc,'dense_rois_in_nuc'))
        os.makedirs(os.path.join(save_loc,'dense_rois_in_band'))
        os.makedirs(os.path.join(save_loc,'measurements'))
    except:
        pass

Load in data and filter out masks touching border and small labeled areas created during ground truth annotation

In [65]:
img_files = sorted(glob("E:/Fondufe-Mittendorf_Lab/OIC-158_TEM_Nuclei_Segmentation/TEM_Images/Images/*.tif"))
mask_files = sorted(glob("E:/Fondufe-Mittendorf_Lab/OIC-158_TEM_Nuclei_Segmentation/TEM_Images/Masks/*.tif"))
match_image_file = "E:/Fondufe-Mittendorf_Lab/OIC-158_TEM_Nuclei_Segmentation/TEM_Images/Images/2-4-1.tif"
match_image = imread(match_image_file)
match_image_array = np.asarray(match_image, dtype=np.uint16)
imgs = list(map(imread,img_files))
imgs = [np.asarray(img,dtype=np.uint16) for img in imgs] #make sure all imgs are np compatible arrays
nuclei_masks = list(map(imread,mask_files))
nuclei_masks = [np.asarray(mask,dtype=np.uint16) for mask in nuclei_masks] #make sure all label images are compatible arrays
filtered_nuclei_masks = [sk.segmentation.clear_border(mask) for mask in nuclei_masks]
relabel_nuclei_masks = [sk.measure.label(mask) for mask in filtered_nuclei_masks]
remove_small_objects = [sk.morphology.remove_small_objects(mask, 50) for mask in relabel_nuclei_masks]

E:\Temp\ipykernel_15512\2915007981.py:12: UserWarning: Only one label was provided to `remove_small_objects`. Did you mean to use a boolean array?
  remove_small_objects = [sk.morphology.remove_small_objects(mask, 50) for mask in relabel_nuclei_masks]

In [66]:
footprint = sk.morphology.disk(25)
bands_25 = band_25_pixels(masks=remove_small_objects,footprint=footprint)

In [67]:
dense_roi_masks, matched_hist = norm_and_threshold(imgs,match_image_array)
dense_roi_in_nuclei, dense_roi_in_band = dense_rois_in_nuclei_and_band(dense_roi_masks=dense_roi_masks,band_25_pixels=bands_25,relabel_nuc_masks=remove_small_objects)
merged_stacks = merge_masks_image(imgs,nuclei_masks,remove_small_objects,bands_25,dense_roi_in_nuclei,dense_roi_in_band)

c:\ProgramData\anaconda3\envs\CellPoseCLE-env\lib\site-packages\skimage\filters\thresholding.py:466: RuntimeWarning: divide by zero encountered in log
  crit = np.log(((P1_sq[:-1] * P2_sq[1:]) ** -1) * (P1[:-1] * (1.0 - P1[:-1])) ** 2)

In [ ]:
viewer = napari.view_image(bands_25[4], name='bands')
viewer.add_image(remove_small_objects[4],name='mask')
viewer.add_image(dense_roi_in_nuclei[4],name='threshold')
viewer.add_image(dense_roi_in_band[4],name='threshold_band')
viewer.add_image(imgs[4],name='1-5-1')

In [ ]:
band_props = sk.measure.regionprops(bands_25[0],spacing=[0.0064,0.0064])
band_props[2].area

In [68]:
all_heterochromatin_areas, all_band_areas, all_norm_areas = heterochromatin_and_band_areas(dense_roi_in_band,bands_25,scale=[0.0064,0.0064])

In [70]:
#collecting measurements for all images
props = ['label', 'area', 'eccentricity', 'equivalent_diameter_area','extent','perimeter','solidity','intensity_max']
scale = [0.0064,0.0064] #in um
save_loc = 'Results/'
create_folders(save_loc=save_loc)
for i in range(len(imgs)):
    df = get_measurements(merged_stacks[i],props=props,scale=scale,all_heterochromatin_areas=all_heterochromatin_areas[i], all_band_areas=all_band_areas[i], all_norm_areas=all_norm_areas[i])
    save_df_and_images(df,matched_hist=matched_hist[i],bands=bands_25[i],dense_roi_in_nuclei=dense_roi_in_nuclei[i],dense_roi_in_band=dense_roi_in_band[i],save_loc=save_loc,img_files=img_files[i])

## Merging and summarizing data

In [85]:
control_files = sorted(glob("Results/measurements/measurements_1-*.csv"))
arsenic_transformed_files = sorted(glob("Results/measurements/measurements_2-*.csv"))
satb2_oe_files = sorted(glob("Results/measurements/measurements_3-*.csv"))
circ_oe_files = sorted(glob("Results/measurements/measurements_4-*.csv"))
satb2_kd_files = sorted(glob("Results/measurements/measurements_5-*.csv"))
satb2_circ_files = sorted(glob("Results/measurements/measurements_6-*.csv"))

In [122]:
control_df = list(map(pd.read_csv,control_files))
arsenic_transformed_df = list(map(pd.read_csv,arsenic_transformed_files))
satb2_oe_df = list(map(pd.read_csv,satb2_oe_files))
circ_oe_df = list(map(pd.read_csv,circ_oe_files))
satb2_kd_df = list(map(pd.read_csv,satb2_kd_files))
satb2_circ_df = list(map(pd.read_csv,satb2_circ_files))

In [91]:
len(control_df)

5

In [ ]:
    #controls
for i in range(len(control_files)):
    file_name = os.path.basename(control_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(control_df[i],1,'Sample_ID',name)
    #arsenic
for i in range(len(arsenic_transformed_files)):
    file_name = os.path.basename(arsenic_transformed_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(arsenic_transformed_files[i],1,'Sample_ID',name)
    #satb2 OE
for i in range(len(satb2_oe_files)):
    file_name = os.path.basename(control_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(control_df[i],1,'Sample_ID',name)
    #circ OE
for i in range(len(control_files)):
    file_name = os.path.basename(control_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(control_df[i],1,'Sample_ID',name)
    #satb2 KD
for i in range(len(control_files)):
    file_name = os.path.basename(control_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(control_df[i],1,'Sample_ID',name)
    #satb2 circ co expression
for i in range(len(control_files)):
    file_name = os.path.basename(control_files[i])
    name = file_name[13:-4]
    pd.DataFrame.insert(control_df[i],1,'Sample_ID',name)

In [100]:
control_df[0].head()

,Sample_ID,Unnamed: 0,object_ID,Nuc_area_um^2,eccentricity,equivalent_diameter_area_um^2,extent,perimeter_um,solidity,Image_intensity_max,Cell_ID,Nuc_region_ID,Band_ID,Dense_nuc_regions_ID,Heterochromatin_band_ID,nuc_circularity,heterochromatin_area_in_band_um^2,25-pixel_band_area_um^2,norm_area_heterochromatin_in_band
0,1-1-1,0,1,65.529651,0.609783,9.134273,0.619663,87.361947,0.830544,16136.0,2.0,1.0,1.0,1.0,1.0,0.107895,6.926090,13.295206,0.520946
1,1-1-1,1,2,1.071636,0.739564,1.168097,0.699807,4.061973,0.985461,13891.0,1.0,2.0,2.0,2.0,4.0,0.816175,0.272712,0.537395,0.507470

In [117]:
control_merged_df = pd.concat(control_df)

In [114]:
control_merged_df.head()

,Unnamed: 0,Sample_ID,object_ID,Nuc_area_um^2,eccentricity,equivalent_diameter_area_um^2,extent,perimeter_um,solidity,Image_intensity_max,Cell_ID,Nuc_region_ID,Band_ID,Dense_nuc_regions_ID,Heterochromatin_band_ID,nuc_circularity,heterochromatin_area_in_band_um^2,25-pixel_band_area_um^2,norm_area_heterochromatin_in_band
0,0,1-1-1,1,65.529651,0.609783,9.134273,0.619663,87.361947,0.830544,16136.0,2.0,1.0,1.0,1.0,1.0,0.107895,6.926090,13.295206,0.520946
1,1,1-1-1,2,1.071636,0.739564,1.168097,0.699807,4.061973,0.985461,13891.0,1.0,2.0,2.0,2.0,4.0,0.816175,0.272712,0.537395,0.507470
0,0,1-2-1,1,47.331860,0.665767,7.763040,0.693858,37.223470,0.944555,14588.0,1.0,1.0,1.0,1.0,1.0,0.429269,4.257833,5.562696,0.765426
0,0,1-3-1,1,66.506547,0.869422,9.202107,0.517647,51.459541,0.836237,14564.0,1.0,1.0,1.0,1.0,1.0,0.315604,5.212201,7.737262,0.673649
0,0,1-4-1,1,47.730852,0.698265,7.795692,0.652095,38.299424,0.865103,12960.0,1.0,1.0,1.0,1.0,1.0,0.408907,3.270902,5.713019,0.572535

In [120]:
control_merged_df.drop(columns='Unnamed: 0',inplace=True)

In [121]:
control_merged_df.head()

,Sample_ID,object_ID,Nuc_area_um^2,eccentricity,equivalent_diameter_area_um^2,extent,perimeter_um,solidity,Image_intensity_max,Cell_ID,Nuc_region_ID,Band_ID,Dense_nuc_regions_ID,Heterochromatin_band_ID,nuc_circularity,heterochromatin_area_in_band_um^2,25-pixel_band_area_um^2,norm_area_heterochromatin_in_band
0,1-1-1,1,65.529651,0.609783,9.134273,0.619663,87.361947,0.830544,16136.0,2.0,1.0,1.0,1.0,1.0,0.107895,6.926090,13.295206,0.520946
1,1-1-1,2,1.071636,0.739564,1.168097,0.699807,4.061973,0.985461,13891.0,1.0,2.0,2.0,2.0,4.0,0.816175,0.272712,0.537395,0.507470
0,1-2-1,1,47.331860,0.665767,7.763040,0.693858,37.223470,0.944555,14588.0,1.0,1.0,1.0,1.0,1.0,0.429269,4.257833,5.562696,0.765426
0,1-3-1,1,66.506547,0.869422,9.202107,0.517647,51.459541,0.836237,14564.0,1.0,1.0,1.0,1.0,1.0,0.315604,5.212201,7.737262,0.673649
0,1-4-1,1,47.730852,0.698265,7.795692,0.652095,38.299424,0.865103,12960.0,1.0,1.0,1.0,1.0,1.0,0.408907,3.270902,5.713019,0.572535